call ccl samples/helloWorld.cl2
call ccl samples/functionSample.cl2
call ccl samples/structSample.cl2
call ccl samples/lookupSample.cl2
call ccl samples/castSample.cl2
call ccl samples/defaultParamSample.cl2
call ccl samples/handleErrors.cl2
call ccl samples/throwSample.cl2
call ccl samples/propertySample.cl2
call ccl samples/regexSample.cl2